### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by armen181** [scjtqs2/Hackintosh_ONDA-H410D4-IPC_15-10500_UDH630#3]
Hello, thanks for your work, I have the same build as you but the audio not working, Mac OS does not detect any audio driver. 
Ventura 13.3

**Comment by scjtqs2** [comment]
> Hello, thanks for your work, I have the same build as you but the audio not working, Mac OS does not detect any audio driver. Ventura 13.3

Maybe,you need `AppleALC.kext` with 'boot-args' for `alcid=5`
My audio worked well on Ventura 13.3

**Comment by armen181** [comment]
I had 1 board of Onda h410d4 IPC and it has not working audio, I use USB audio card, yesterday I build a second Hackintosh, and again audio not working. Today I will install Windows and check if Windows can detect the audio drivers.
Is your audio card Realtek ALC883?

**Comment by scjtqs2** [comment]
> I had 1 board of Onda h410d4 IPC and it has not working audio, I use USB audio card, yesterday I build a second Hackintosh, and again audio not working. Today I will install Windows and check if Windows can detect the audio drivers. Is your audio card Realtek ALC883?

No,just for Reaitek ALC662

**Comment by scjtqs2** [comment]
> I had 1 board of Onda h410d4 IPC and it has not working audio, I use USB audio card, yesterday I build a second Hackintosh, and again audio not working. Today I will install Windows and check if Windows can detect the audio drivers. Is your audio card Realtek ALC883?

ALC883。 Maybe,you need AppleALC.kext with 'boot-args' for `alcid=7` or `alcid=20`

**Comment by armen181** [comment]
I think new board comes with alc883, thanks I will test it.

![20230419_095638](https://user-images.githubusercontent.com/5547970/233009126-4d15aa10-753d-4a2d-9152-289ea198dd94.jpg)

**Comment by armen181** [comment]
Confirm, alcid=7 fixes the audio.

![image](https://user-images.githubusercontent.com/5547970/233043792-86954022-effe-4c93-926e-07a3d9345f3f.png)
