### ISSUE TITLE
Problems with DVI Monitors

### ISSUE THREAD

**Issue by axlsml** [scjtqs2/Hackintosh_ONDA-H410D4-IPC_15-10500_UDH630#6]
I am observing the following issues with two samsung monitors (using DVI - HDMI and DVI - DP Adapter cables):

* intellij idea fullscreen does not work. everytime I enter fullscreen, the screen will turn black and stay black
* out of nowhere today, both screens are not working anymore. BIOS + boot screen are still on but then they stay black after boot. I cant login anymore

**Comment by scjtqs2** [comment]
Use hackintool to imitate the graphics card to patch the buffer frame

**Comment by axlsml** [comment]
I think it was something with my cables. Although Windows worked well. I did not need to patch frame buffer.

I replaced one cable (DVI / DP adapter) with a new one (DP / DP without adapter).
Also maybe the second cable (DVI / HDMI adapter) might have been a bit shaky. I inserted the hdmi adapter very tight.

Now everything works perfectly. No flickering and also fullscreen no problems. Thanks.
